services:

  db:
    image: docker.io/postgres:16.4-bookworm
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/etc/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users_service

networks:
  backend:
    name: backend 
    attachable: true