INSERT INTO users (
    id,
    primaryEmail,
    password,
    hashFunction,
    isAdmin,
    isDelegatedAdmin,
    agreedToTerms,
    suspended,
    changePasswordAtNextLogin,
    ipWhitelisted,
    kind,
    isMailboxSetup,
    customerId,
    lastLoginTime,
    suspensionReason,
    thumbnailPhotoUrl,
    creationTime,
    archived,
    orgUnitPath,
    recoveryEmail,
    recoveryPhone,
    deletionTime,
    name,
    emails,
    externalIds,
    relations,
    addresses,
    organizations,
    phones,
    languages,
    posixAccounts,
    sshPublicKeys,
    notes,
    websites,
    locations,
    keywords,
    ims,
    customSchemas,
    aliases,
    nonEditableAliases
) VALUES
    ('user1', 'user1@example.com', 'passwordHash1', 'SHA-256', FALSE, FALSE, TRUE, FALSE, TRUE, FALSE, 'user', FALSE, 'cust123', NOW(), NULL, 'http://example.com/photo1.jpg', NOW(), FALSE, '/org1', 'recovery1@example.com', '123-456-7890', NULL,
    '{"first": "John", "last": "Doe"}', 
    '[{"email": "user1@example.com"}]', 
    '[{"id": "ext123", "source": "sourceA"}]', 
    '[{"relation": "friend", "id": "user2"}]', 
    '[{"street": "123 Main St", "city": "Anytown", "state": "CA", "zip": "12345"}]', 
    '[{"name": "Org1", "role": "member"}]', 
    '[{"type": "mobile", "number": "555-1234"}]', 
    '[{"language": "English"}]', 
    '[{"accountType": "user", "username": "posixuser1"}]', 
    '[{"key": "ssh-rsa AAAAB3... user1"}]', 
    '[{"notes": "Some notes about user1."}]', 
    '[{"website": "http://example1.com"}]', 
    '[{"location": "Office"}]', 
    '[{"keyword": "developer"}]', 
    '[{"im": "skype:user1"}]', 
    '[{"schema": "customSchema1"}]', 
    '["alias1@example.com", "alias2@example.com"]', 
    '["noneditable1@example.com"]'),

    ('user2', 'user2@example.com', 'passwordHash2', 'SHA-256', TRUE, FALSE, TRUE, FALSE, FALSE, TRUE, 'user', TRUE, 'cust456', NOW(), 'Account compromised', 'http://example.com/photo2.jpg', NOW(), TRUE, '/org2', 'recovery2@example.com', '987-654-3210', NULL,
    '{"first": "Jane", "last": "Smith"}', 
    '[{"email": "user2@example.com"}]', 
    '[{"id": "ext456", "source": "sourceB"}]', 
    '[{"relation": "colleague", "id": "user3"}]', 
    '[{"street": "456 Elm St", "city": "Othertown", "state": "NY", "zip": "67890"}]', 
    '[{"name": "Org2", "role": "admin"}]', 
    '[{"type": "home", "number": "555-5678"}]', 
    '[{"language": "Spanish"}]', 
    '[{"accountType": "user", "username": "posixuser2"}]', 
    '[{"key": "ssh-rsa AAAAB3... user2"}]', 
    '[{"notes": "Some notes about user2"}]', 
    '[{"website": "http://example2.com"}]', 
    '[{"location": "Remote"}]', 
    '[{"keyword": "manager"}]', 
    '[{"im": "skype:user2"}]', 
    '[{"schema": "customSchema2"}]', 
    '["alias3@example.com"]', 
    '["noneditable2@example.com"]'),

    ('user3', 'user3@example.com', 'passwordHash3', 'SHA-256', FALSE, TRUE, TRUE, TRUE, TRUE, FALSE, 'user', TRUE, 'cust789', NOW(), NULL, 'http://example.com/photo3.jpg', NOW(), FALSE, '/org3', 'recovery3@example.com', '321-654-0987', NULL,
    '{"first": "Alice", "last": "Johnson"}', 
    '[{"email": "user3@example.com"}]', 
    '[{"id": "ext789", "source": "sourceC"}]', 
    '[{"relation": "family", "id": "user4"}]', 
    '[{"street": "789 Oak St", "city": "Thirdtown", "state": "TX", "zip": "23456"}]', 
    '[{"name": "Org3", "role": "member"}]', 
    '[{"type": "work", "number": "555-8765"}]', 
    '[{"language": "French"}]', 
    '[{"accountType": "user", "username": "posixuser3"}]', 
    '[{"key": "ssh-rsa AAAAB3... user3"}]', 
    '[{"notes": "Some notes about user3"}]', 
    '[{"website": "http://example3.com"}]', 
    '[{"location": "Home"}]', 
    '[{"keyword": "designer"}]', 
    '[{"im": "skype:user3"}]', 
    '[{"schema": "customSchema3"}]', 
    '[]', 
    '[]'),

    ('user4', 'user4@example.com', 'passwordHash4', 'SHA-256', TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, 'user', TRUE, 'cust012', NOW(), 'Inactive', 'http://example.com/photo4.jpg', NOW(), TRUE, '/org4', 'recovery4@example.com', '654-321-0987', NULL,
    '{"first": "Bob", "last": "Brown"}', 
    '[{"email": "user4@example.com"}]', 
    '[{"id": "ext012", "source": "sourceD"}]', 
    '[{"relation": "friend", "id": "user5"}]', 
    '[{"street": "101 Pine St", "city": "Fourthtown", "state": "FL", "zip": "34567"}]', 
    '[{"name": "Org4", "role": "member"}]', 
    '[{"type": "mobile", "number": "555-4321"}]', 
    '[{"language": "German"}]', 
    '[{"accountType": "user", "username": "posixuser4"}]', 
    '[{"key": "ssh-rsa AAAAB3... user4"}]', 
    '[{"notes": "Some notes about user4"}]', 
    '[{"website": "http://example4.com"}]', 
    '[{"location": "Office"}]', 
    '[{"keyword": "analyst"}]', 
    '[{"im": "skype:user4"}]', 
    '[{"schema": "customSchema4"}]', 
    '["alias4@example.com"]', 
    '["noneditable4@example.com"]'),

    ('user5', 'user5@example.com', 'passwordHash5', 'SHA-256', FALSE, FALSE, TRUE, FALSE, TRUE, FALSE, 'user', FALSE, 'cust345', NOW(), NULL, 'http://example.com/photo5.jpg', NOW(), FALSE, '/org5', 'recovery5@example.com', '432-109-8765', NULL,
    '{"first": "Carol", "last": "Williams"}', 
    '[{"email": "user5@example.com"}]', 
    '[{"id": "ext345", "source": "sourceE"}]', 
    '[{"relation": "colleague", "id": "user1"}]', 
    '[{"street": "202 Maple St", "city": "Fifthtown", "state": "WA", "zip": "45678"}]', 
    '[{"name": "Org5", "role": "admin"}]', 
    '[{"type": "home", "number": "555-5670"}]', 
    '[{"language": "Italian"}]', 
    '[{"accountType": "user", "username": "posixuser5"}]', 
    '[{"key": "ssh-rsa AAAAB3... user5"}]', 
    '[{"notes": "Some notes about user5"}]', 
    '[{"website": "http://example5.com"}]', 
    '[{"location": "Remote"}]', 
    '[{"keyword": "developer"}]', 
    '[{"im": "skype:user5"}]', 
    '[{"schema": "customSchema5"}]', 
    '[]', 
    '[]');
